version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # Public HTTP Port:
      - '80:80'
      # Public HTTPS Port:
      - '443:443'
      # Admin Web Port:
      - '81:81'
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      # These are the settings to access your db
      DB_MYSQL_HOST: $DB_HOST
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: $DB_USER
      DB_MYSQL_PASSWORD: $DB_PASSWORD
      DB_MYSQL_NAME: $DB_NAME
      # If you would rather use Sqlite uncomment this
      # and remove all DB_MYSQL_* lines above
      # DB_SQLITE_FILE: "/data/database.sqlite"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: $SQL_ROOT_PASSWORD
      MYSQL_DATABASE: $SQL_DATABASE
      MYSQL_USER: $SQL_USER
      MYSQL_PASSWORD: $SQL_PASSWORD
    volumes:
      - ./data/mysql:/var/lib/mysql

  ombi:
    image: ghcr.io/linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
#      - BASE_URL=/ombi #optional
    volumes:
      - /docker/ombi/config:/config
    ports:
      - 3579:3579
    restart: unless-stopped

  tautulli:
    image: ghcr.io/linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - /docker/tautulli/config:/config
    ports:
      - 8181:8181
    restart: unless-stopped

  mc:
    image: itzg/minecraft-server
    container_name: minecraft
    ports:
      - 25565:25565
    environment:
      MEMORY: "4G"
      EULA: "TRUE"
      MOTD: $MOTD
      ENABLE_RCON: "false"
    tty: true
    stdin_open: true
    restart: unless-stopped

  ubooquity:
    image: ghcr.io/linuxserver/ubooquity
    container_name: ubooquity
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - /docker/books:/config
      - /docker/books:/books
      - /docker/comics:/comics
      - /docker/files:/files
    ports:
      - 2202:2202
      - 2203:2203
    restart: unless-stopped

#  valheim:
#    image: mbround18/valheim:latest
#    ports:
#      - 2456:2456/udp
#      - 2457:2457/udp
#      - 2458:2458/udp
#    environment:
#      - PORT=2456
#      - NAME=$VAL_NAME
#      - WORLD=$VAL_WORLD
#      - PASSWORD=$VAL_PASSWORD
#      - TZ=America/Denver
#      - PUBLIC=0
#      - AUTO_UPDATE=1
#      - AUTO_UPDATE_SCHEDULE="0 1 * * *"
#      - AUTO_BACKUP=1
#      - AUTO_BACKUP_SCHEDULE="*/15 * * * *"
#      - AUTO_BACKUP_REMOVE_OLD=1
#      - AUTO_BACKUP_DAYS_TO_LIVE=3
#      - AUTO_BACKUP_ON_UPDATE=1
#      - AUTO_BACKUP_ON_SHUTDOWN=1
#    volumes:
#      - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
#      - ./valheim/server:/home/steam/valheim
#      - ./valheim/backups:/home/steam/backups

#  valheim: 
#    image: ghcr.io/lloesche/valheim-server
#    cap_add:
#      - sys_nice
#    volumes: 
#      - ./valheim-server/config:/config
#      - ./valheim-server/data:/opt/valheim
#    ports: 
#      - "2456-2457:2456-2457/udp"
#      - "9001:9001/tcp"
#    env_file:
#      - ./valheim-server/valheim.env
#    restart: always
#    stop_grace_period: 2m

#  prowlarr:
#    image: ghcr.io/linuxserver/prowlarr:develop
#    container_name: prowlarr
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=America/Denver
#    volumes:
#      - /docker/prowlarr/config:/config
#    ports:
#      - 9696:9696
#    restart: unless-stopped

#  minecraft:
#    ports:
#      - "25565:25565"
#    volumes:
#      - "mcbig:/data"
#    environment:
#      MOTD: $MOTD
#      EULA: "TRUE"
#      MAX_MEMORY: 32G
#      MAX_BUILD_HEIGHT: 256
#      VIEW_DISTANCE: 15
#      LEVEL_TYPE: LARGEBIOMES
#      MAX_PLAYERS: 100
#      CONSOLE: "false"
#    image: itzg/minecraft-server
#    restart: always
#  rcon:
#    image: itzg/rcon
#    ports:
#      - "4326:4326"
#      - "4327:4327"
#    volumes:
#      - "rcon:/opt/rcon-web-admin/db"

# volumes:
 # mcbig:
 # rcon:

  terraria:
    image: beardedio/terraria:tshock-latest
    ports:
      - '7777:7777'
    restart: unless-stopped
    environment:
      - password=$TERRARIA_PASSWORD
      - world=$TERRARIA_WORLD
    volumes:
      - ./terraria/config-tshock:/config
    tty: true
    stdin_open: true

#  babybuddy:
#    image: lscr.io/linuxserver/babybuddy:latest
#    container_name: babybuddy
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=America/Denver
#      - CSRF_TRUSTED_ORIGINS=https://url.com
#    volumes:
#      - $HOME/babybuddy/appdata:/config
#    ports:
#      - 8000:8000
#    restart: unless-stopped

#  factorio:
#    image: factoriotools/factorio
#    ports:
#      - "34197:34197/udp"
#      - "27015:27015/tcp"
#    volumes:
#      - /docker/factorio:/factorio
